### ISSUE TITLE
你自己的演示页面访问服务出错

### ISSUE THREAD

**Issue by zhuxindong** [elunez/openai-java#10]
![image](https://user-images.githubusercontent.com/24989246/222616680-f1cae131-7520-4561-9fa9-1e038c81fd2b.png)

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/24989246/222616680-f1cae131-7520-4561-9fa9-1e038c81fd2b.png)

已经恢复了，有问题随时反馈
