### ISSUE TITLE
一直在转，连接请求失败

### ISSUE THREAD

**Issue by NullPointerException-Jy** [elunez/openai-java#15]
![image](https://user-images.githubusercontent.com/79494162/223683282-821423a3-043e-46d3-b948-ffd3f8ce8cf7.png)
![image](https://user-images.githubusercontent.com/79494162/223683464-05a50c9a-6da0-4dcf-baef-43faa7aefb4d.png)

**Comment by elunez** [comment]
```
使用Cloudflare服务
新建一个 Cloudflare Worker
将 https://gist.github.com/noobnooc/d0407b5fb81cff9d36f981170b99d4e6 里的代码粘贴到 Worker 中并部署
给 Worker 绑定一个没有被 GFW 认证的域名
使用自己的域名代替 api.openai.com
```
https://github.com/noobnooc/noobnooc/discussions/9
