### ISSUE TITLE
模型是否没有更新到gpt3.5

### ISSUE THREAD

**Issue by MRZHUH** [elunez/openai-java#19]
![image](https://user-images.githubusercontent.com/37842169/225833385-78d36c9e-5b17-451d-a85e-4ef786598453.png)
![image](https://user-images.githubusercontent.com/37842169/225833399-b19b4f07-340a-438d-ae47-7ff1a4b7e0b3.png)
模型是否没有更新到gpt3.5

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/37842169/225833385-78d36c9e-5b17-451d-a85e-4ef786598453.png) ![image](https://user-images.githubusercontent.com/37842169/225833399-b19b4f07-340a-438d-ae47-7ff1a4b7e0b3.png) 模型是否没有更新到gpt3.5

可以自己看代码，目前用的就是3.5模型
